bot_api_key: '821647258:AAFEQ_L4Fk9kr1oRbT7ay0PUWw3eRgYKLUg'
bot_webhook_url: 'https://telegramfilmsotus.site/hook.php'
bot_username: '@films_choosing_otus_bot'

movie_api_key: '14a355e01638761caa047b29b68efb6f'
movie_api_url: 'https://lyagusha.com/movies'

mysql_credentials:
  host: '127.0.0.1'
  port: 3306
  user: 'ruben'
  password: 'lnlakkk111'
  database: 'bot_db'
